### PR TITLE
Add grids to more entities

### PR DESCRIPTION
**Pull request by Gultak**
Add grids to locomotives, fluid wagons and artillery wagons. Also adds some inventory slots to artillery wagons.

You may want to add separate options to activate/configure these (or ask me to do that). For my use case just adding them is sufficient,

### CODE REVIEW

**Comment by TheBrutalX** [comment]
The new version is online 🎉

**Comment by Gultak** [comment]
Thanks a lot!

Can you elaborate on why it's buggy for locomotives? I use my patched version im my game currently and it looks to work just fine...

**Comment by Gultak** [comment]
Were you in map mode? When in map mode, clicking on the items adds a pickup task for robots instead of actually picking them up by yourself.

It may also happen like that in general. I never used the rail grids when actually on the planet for now :)

**Comment by TheBrutalX** [comment]
To access the grid is need to open the locomotive gui and open the fuel panel, for this reason seems i'm the map mode

**Comment by Gultak** [comment]
Aye - then it's probably a Factorio limitation.

In that case I'd add that as a config switch ("Add grid to locomotives") with a comment that you can't manually pick up items from the grid on locomotives due to a game restriction.

**Comment by TheBrutalX** [comment]
Hi, sorry for the delay, I tried to see if it was possible to integrate it effectively.
I tried to open a ticket to the developers and see if it will be a more stable feature in the future

**Pull request merged**
